### ISSUE TITLE
remote data

### ISSUE THREAD

**Issue by softcmrc** [CodyHouse/cd-explorer-changelog#1]
I'd like to adapt this for an ecommerce website search, is there a sample, how to fill the array with an ajax call with json result - would be helpful, thx.

**Comment by claudia-romano** [comment]
Hi there,
do you have doubts about how to perform the ajax request or how to convert the json response to an array that you can pass to the explorer? Thanks.

**Comment by softcmrc** [comment]
.. how to perform the ajax request within your search function correctly ... use jquery?

**Comment by claudia-romano** [comment]
Thanks for the clarification, sure you can use jquery if you are familiar with `$.ajax`. The component does not use jquery but it is perfectly compatible with it.
